import os from 'node:os'
import path from 'node:path'

import fs from 'fs-extra'
import sharp from 'sharp'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

import { Lifecycle } from '../../src/core/Lifecycle'
import { PicGo } from '../../src/core/PicGo'
import type { IImgInfo, IPicGo } from '../../src/types'
import { IBusEvent } from '../../src/utils/enum'
import { eventBus } from '../../src/utils/eventBus'

describe('Lifecycle', () => {
  const baseDirs: string[] = []

  afterEach(async () => {
    await Promise.all(baseDirs.map(baseDir => fs.remove(baseDir)))
    baseDirs.length = 0
  })

  function createLifecycle(): Lifecycle {
    const baseDir = path.join(os.tmpdir(), `piclist-lifecycle-${Date.now()}-${Math.random().toString(36).slice(2)}`)
    baseDirs.push(baseDir)

    return new Lifecycle({
      baseDir,
      getConfig: () => undefined,
    } as any)
  }

  it('should preprocess AV1-compressed HEIF files generated by image conversion', async () => {
    const lifecycle = createLifecycle()
    const tempFilePath = path.join(baseDirs[0], 'piclistTemp')
    const input = await sharp({
      create: {
        width: 2,
        height: 2,
        channels: 3,
        background: { r: 255, g: 0, b: 0 },
      },
    })
      .jpeg()
      .toBuffer()
    const heif = await sharp(input)
      .toFormat('heif', {
        quality: 80,
        compression: 'av1',
      })
      .toBuffer()
    const errors: string[] = []
    const ctx = {
      log: {
        error: (message: string) => errors.push(message),
      },
    }

    const output = await (lifecycle as any).convertHeicAndCompress(
      heif,
      path.join(tempFilePath, 'converted.heif'),
      '.heif',
      tempFilePath,
      { isConvert: true, convertFormat: 'heif', quality: 80 },
      ctx,
    )
    const metadata = await sharp(output).metadata()

    expect(errors).toHaveLength(0)
    expect(metadata.format).toBe('heif')
    expect(output.subarray(4, 12).toString('ascii')).toBe('ftypavif')
  })

  it('should detect image type from magic number for local files without extension', async () => {
    const lifecycle = createLifecycle()
    const tempFilePath = path.join(baseDirs[0], 'piclistTemp')
    await fs.ensureDir(tempFilePath)
    const input = await sharp({
      create: {
        width: 3,
        height: 2,
        channels: 3,
        background: { r: 255, g: 255, b: 0 },
      },
    })
      .png()
      .toBuffer()
    const inputPath = path.join(baseDirs[0], 'image-without-extension')
    await fs.outputFile(inputPath, input)
    const ctx = {
      input: [inputPath],
      rawInputPath: [],
      log: {
        info: () => undefined,
        error: () => undefined,
      },
    }

    await (lifecycle as any).processImage(
      inputPath,
      0,
      ctx,
      tempFilePath,
      { isConvert: true, convertFormat: 'jpg' },
      undefined,
      new Set(),
    )
    const metadata = await sharp(ctx.input[0]).metadata()

    expect(ctx.rawInputPath[0]).toBe(path.join(baseDirs[0], 'image-without-extension.jpg'))
    expect(ctx.input[0]).toBe(path.join(tempFilePath, 'image-without-extension.jpg'))
    expect(metadata.format).toBe('jpeg')
  })
})

describe('Lifecycle preprocessing isolation', () => {
  let baseDir: string
  let picgo: PicGo
  let inputPaths: string[]
  let inputBuffers: Buffer[]
  let uploaded: IImgInfo[]
  let listeners: Set<(...args: any[]) => void>

  beforeEach(async () => {
    listeners = new Set(eventBus.listeners(IBusEvent.CONFIG_CHANGE))
    baseDir = await fs.mkdtemp(path.join(os.tmpdir(), 'piclist-preprocessing-'))
    await fs.writeJson(path.join(baseDir, 'config.json'), {
      silent: true,
      debug: true,
      picBed: { current: 'test', uploader: 'test', test: { _id: 'test' } },
      picgoPlugins: {},
      buildIn: { compress: { isReSizeByPercent: true, reSizePercent: 50 } },
    })
    picgo = await PicGo.create(path.join(baseDir, 'config.json'))
    uploaded = []
    picgo.helper.uploader.register('test', {
      handle: async ctx => {
        uploaded.push(...ctx.output.map(item => ({ ...item })))
      },
    })
    inputPaths = ['a', 'b'].map(folder => path.join(baseDir, folder, 'photo.png'))
    inputBuffers = await Promise.all(
      ['red', 'blue'].map(background =>
        sharp({ create: { width: 8, height: 6, channels: 3, background } })
          .png()
          .toBuffer(),
      ),
    )
    await Promise.all(inputPaths.map((inputPath, index) => fs.outputFile(inputPath, inputBuffers[index])))
  })

  afterEach(async () => {
    vi.restoreAllMocks()
    for (const listener of eventBus.listeners(IBusEvent.CONFIG_CHANGE)) {
      if (!listeners.has(listener)) eventBus.removeListener(IBusEvent.CONFIG_CHANGE, listener)
    }
    await fs.remove(baseDir)
  })

  async function expectDistinctImages(images: IImgInfo[]): Promise<void> {
    expect(images).toHaveLength(2)
    expect(images[0].buffer!.equals(images[1].buffer!)).toBe(false)
    expect(new Set(images.map(item => item.filePath)).size).toBe(2)
    for (const [index, item] of images.entries()) {
      const { data, info } = await sharp(item.buffer!).removeAlpha().raw().toBuffer({ resolveWithObject: true })
      expect(info).toMatchObject({ width: 4, height: 3, channels: 3 })
      expect([...data.subarray(0, 3)]).toEqual(index === 0 ? [255, 0, 0] : [0, 0, 255])
    }
  }

  it.each([undefined, '{uuid}', '{localFolder}/{filename}'])(
    'preserves distinct same-name images through upload with rename format %s',
    async format => {
      if (format) picgo.saveConfig({ 'buildIn.rename': { enable: true, format } })

      const { ctx } = await picgo.uploadReturnCtx([...inputPaths])

      await expectDistinctImages(uploaded)
      expect(ctx?.rawInputPath).toEqual(inputPaths)
      if (format === '{uuid}') {
        expect(new Set(uploaded.map(item => item.fileName)).size).toBe(2)
        for (const item of uploaded) expect(item.fileName).toMatch(/^[a-f\d]{32}\.png$/)
      } else {
        expect(uploaded.map(item => item.fileName)).toEqual(
          format ? ['a/photo.png', 'b/photo.png'] : ['photo.png', 'photo.png'],
        )
      }
    },
  )

  it('isolates concurrent uploads before either transformer reads the processed files', async () => {
    let release!: () => void
    let arrivals = 0
    const ready = new Promise<void>(resolve => (release = resolve))
    picgo.helper.beforeTransformPlugins.register('wait-for-both-uploads', {
      handle: async () => {
        if (++arrivals === 2) release()
        await ready
      },
    })

    const results = await Promise.all(inputPaths.map(inputPath => picgo.uploadReturnCtx([inputPath])))

    await expectDistinctImages(results.map(result => result.ctx!.processedInput[0]))
    expect(uploaded).toHaveLength(2)
  })

  it('preserves different URL images with the same basename', async () => {
    const urls = ['https://example.invalid/a/photo.png', 'https://example.invalid/b/photo.png']
    vi.spyOn(picgo.Request, 'request').mockImplementation((async ({ url }: { url: string }) => ({
      data: inputBuffers[urls.indexOf(url)],
      headers: { 'content-type': 'image/png' },
    })) as IPicGo['request'])

    await picgo.uploadReturnCtx(urls)

    await expectDistinctImages(uploaded)
    expect(uploaded.map(item => item.fileName)).toEqual(['photo.png', 'photo.png'])
  })

  it('isolates images whose output names collide after format conversion', async () => {
    const otherPath = path.join(baseDir, 'a', 'photo.webp')
    await fs.outputFile(otherPath, await sharp(inputBuffers[1]).webp({ lossless: true }).toBuffer())
    picgo.saveConfig({ 'buildIn.compress.isConvert': true, 'buildIn.compress.convertFormat': 'png' })

    const { ctx } = await picgo.uploadReturnCtx([inputPaths[0], otherPath])

    await expectDistinctImages(uploaded)
    expect(uploaded.map(item => item.fileName)).toEqual(['photo.png', 'photo.png'])
    expect(ctx?.rawInputPath).toEqual([inputPaths[0], inputPaths[0]])
  })

  it.each([
    { format: '{filename}', processing: 'none' },
    { format: '{localFolder}/{filename}', processing: 'none' },
    { format: '{localFolder}/{filename}', processing: 'resize' },
    { format: '{localFolder}/{filename}', processing: 'convert' },
  ])('renames surviving batch inputs with $format and $processing processing', async ({ format, processing }) => {
    if (processing === 'none') picgo.unsetConfig('buildIn', 'compress')
    if (processing === 'convert') {
      picgo.setConfig({ 'buildIn.compress.isConvert': true, 'buildIn.compress.convertFormat': 'jpg' })
    }
    picgo.setConfig({ 'buildIn.rename': { enable: true, format } })
    const secondPath = path.join(baseDir, 'b', 'other.png')
    await fs.outputFile(secondPath, inputBuffers[1])
    const inputs = [
      path.join(baseDir, 'missing-first', 'missing.png'),
      inputPaths[0],
      path.join(baseDir, 'missing-middle', 'missing.webp'),
      secondPath,
      path.join(baseDir, 'missing-last', 'missing.jpg'),
    ]

    const { ctx } = await picgo.uploadReturnCtx([...inputs])

    const extension = processing === 'convert' ? 'jpg' : 'png'
    expect(uploaded.map(item => item.fileName)).toEqual(
      format === '{filename}' ? ['photo.png', 'other.png'] : [`a/photo.${extension}`, `b/other.${extension}`],
    )
    expect(ctx?.processedInput.map(item => item.fileName)).toEqual(uploaded.map(item => item.fileName))
    expect(ctx?.rawInput).toEqual(inputs)
    expect(ctx?.input).toEqual(inputs)
    expect(ctx?.rawInputPath).toEqual(
      inputs.map(input =>
        processing === 'convert' && [inputPaths[0], secondPath].includes(input)
          ? input.replace(/\.png$/, '.jpg')
          : input,
      ),
    )
  })

  it('keeps the valid filename when the first batch input is missing', async () => {
    picgo.unsetConfig('buildIn', 'compress')
    picgo.setConfig({ 'buildIn.rename': { enable: true, format: '{filename}' } })
    const validPath = path.join(baseDir, 'valid.png')
    await fs.outputFile(validPath, inputBuffers[0])

    await picgo.uploadReturnCtx([path.join(baseDir, 'missing.png'), validPath])

    expect(uploaded).toHaveLength(1)
    expect(uploaded[0].fileName).toBe('valid.png')
    expect(uploaded[0].buffer).toEqual(inputBuffers[0])
  })

  it('retains positional renaming for custom transformers without source indices', async () => {
    picgo.setConfig({
      'picBed.transformer': 'custom',
      'buildIn.rename': { enable: true, format: '{localFolder}/{filename}' },
    })
    picgo.helper.transformer.register('custom', {
      handle: async ctx => {
        ctx.output = await Promise.all(
          ctx.input.map(async input => ({ buffer: await fs.readFile(input), fileName: path.basename(input) })),
        )
      },
    })

    await picgo.uploadReturnCtx([...inputPaths])

    expect(uploaded.map(item => item.fileName)).toEqual(['a/photo.png', 'b/photo.png'])
  })
})
