import os from 'node:os'
import path from 'node:path'

import fs from 'fs-extra'
import sharp from 'sharp'
import { afterEach, describe, expect, it } from 'vitest'

import { Lifecycle } from '../../src/core/Lifecycle'

describe('Lifecycle', () => {
  const baseDirs: string[] = []

  afterEach(async () => {
    await Promise.all(baseDirs.map(baseDir => fs.remove(baseDir)))
    baseDirs.length = 0
  })

  function createLifecycle(): Lifecycle {
    const baseDir = path.join(os.tmpdir(), `piclist-lifecycle-${Date.now()}-${Math.random().toString(36).slice(2)}`)
    baseDirs.push(baseDir)

    return new Lifecycle({
      baseDir,
      getConfig: () => undefined,
    } as any)
  }

  it('should preprocess AV1-compressed HEIF files generated by image conversion', async () => {
    const lifecycle = createLifecycle()
    const tempFilePath = path.join(baseDirs[0], 'piclistTemp')
    const input = await sharp({
      create: {
        width: 2,
        height: 2,
        channels: 3,
        background: { r: 255, g: 0, b: 0 },
      },
    })
      .jpeg()
      .toBuffer()
    const heif = await sharp(input)
      .toFormat('heif', {
        quality: 80,
        compression: 'av1',
      })
      .toBuffer()
    const errors: string[] = []
    const ctx = {
      log: {
        error: (message: string) => errors.push(message),
      },
    }

    const output = await (lifecycle as any).convertHeicAndCompress(
      heif,
      path.join(tempFilePath, 'converted.heif'),
      '.heif',
      tempFilePath,
      { isConvert: true, convertFormat: 'heif', quality: 80 },
      ctx,
    )
    const metadata = await sharp(output).metadata()

    expect(errors).toHaveLength(0)
    expect(metadata.format).toBe('heif')
    expect(output.subarray(4, 12).toString('ascii')).toBe('ftypavif')
  })
})
